apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: p3-frontend
spec:
  replicas: 1 # Number of pod replicas
  selector:
    matchLabels:
      app: p3-frontend
  template:
    metadata:
      labels:
        app: p3-frontend
    spec:
      containers:
        - name: p3-frontend
          image: vietphuvn/udagram-frontend:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: p3-frontend
spec:
  selector:
    app: p3-frontend
  ports:
    - protocol: TCP
      port: 80 # External port
  type: LoadBalancer # To exposes the service externally