name: CI ReverseProxy

on:
  push:
    branches:
      - main
    paths:
      - "udagram-reverseproxy/**"
  pull_request:
    branches:
      - main
    paths:
      - "udagram-reverseproxy/**"

jobs:
  build-and-push-reverse-proxy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PWD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          cd udagram-reverseproxy
          docker build -t ${{ secrets.DOCKER_USR }}/reverseproxy:v2 .

      # Step 4: Push the Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USR }}/reverseproxy:v2